Hello Rails React PR
tomdan-ai/hello_rails_react pull request #1
Opened 2023-08-23 16:03 UTC by tomdan-ai

In This Milestone the following were implemented:

- Use webpack to set up frontend react
- Use rails to create database and API
- Use react to fetch API created in rails

2023-08-23 16:29 UTC, addod19 commented
## Hi @tomdan-ai, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the README file is not professional

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-23 20:41 UTC, mikethreels requested changes
Hi Tom, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the project.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-23 20:41 UTC, mikethreels commented on README.md
> +This project is [MIT](../MIT) licensed.
- [ ] the link to the MIT license is not working as expected please fix it before requesting another review.

2023-08-23 20:41 UTC, mikethreels commented on Gemfile
- [ ] it looks like you removed the required gem "gem "jsbundling-rails"" please make sure to use it in this project as it is a requirement.

2023-08-23 20:41 UTC, mikethreels commented on package.json
> +    "redux": "^4.2.0",
- [ ] the required dependency "babel-loader" is not installed please make sure to do so.

2023-08-23 20:41 UTC, mikethreels commented on babel.config.js
> +      ],
- [ ] please have a look at [this totorial](https://betterprogramming.pub/react-with-rails-2022-bd28e1fcd355#ad0a) the babel.config.js file should look a lot different and the webpack.config.js file is missing, please make sure to implement these correctly

2023-08-23 20:41 UTC, mikethreels commented on app/views/static/index.html.erb
> +<%= react_component("App") %>
- [ ] the view should only have a div with a class called root, the rest of the application should be rendered by react.

2023-08-23 20:41 UTC, mikethreels commented on app/javascript/packs/application.js
>  console.log('Hello World from Webpacker')
- [ ] please avoid committing any console.log they make your code slower and harder to read.

2023-08-23 20:41 UTC, mikethreels commented on app/javascript/packs/application.js
>  // const imagePath = (name) => images(name, true)
- [ ] please don't push any commented-out code they will make your codebase look unorganised and harder to read.

2023-08-23 20:41 UTC, mikethreels commented on app/javascript/components/App.js
> +}
- [ ] everything should exist in the application.js file not in your app.js file.

2023-08-26 07:08 UTC, uwadonat approved these changes
## Hi @tomdan-ai,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Well organized and clean project ✔️
- Professional readme file ✔️
- No linter errors ✔️

![thanks-awesome](https://github.com/tomdan-ai/hello_rails_react/assets/65860678/0b1d6402-aab5-468a-be91-cf0673c9492e)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-08-26 19:36 UTC, merged